apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-app-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ngx-app-operator
  template:
    metadata:
      labels:
        name: ngx-app-operator
    spec:
      serviceAccountName: ngx-app-operator
      containers:
        - name: ngx-app-operator
          # Replace this with the built image name
          image: docker.io/remkohdev/ngx-app-operator
          command:
          - ngx-app-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ngx-app-operator"
